mysql:
  db: chatnio
  host: po0go0g08owkwogw4g04csg0
  password: bEYwHbeNyCf81ZsJcPk7vgZCRGdqNv52fYfEhX4QymkrOABDq4SLCi3iAP7zlK18
  port: 3306
  user: root
  tls: false

redis:
  host: q48kcc488ckskggw8g0gscsk
  port: 6379
  db: 0
  user: root
  password: MZFBXtmYkTPyuIXMZukGKgS1aFVx6Biz5qpNimR5jJ7MBoPtGhxiHsPJ6DWCvypV


secret: secret
serve_static: true

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
