version: '3'
services:
  chatnio:
    image: programzmh/chatnio:latest 
    restart: always 
    ports:
      - "8094:8094"
    environment:
      MYSQL_HOST: "po0go0g08owkwogw4g04csg0"
      MYSQL_PORT: 3306 
      MYSQL_DB: chatnio 
      MYSQL_USER: root 
      MYSQL_PASSWORD: bEYwHbeNyCf81ZsJcPk7vgZCRGdqNv52fYfEhX4QymkrOABDq4SLCi3iAP7zlK18 
      REDIS_HOST: "q48kcc488ckskggw8g0gscsk"
      REDIS_PORT: 6379 
      SECRET: "secret"
      SERVE_STATIC: "true"
    volumes:
      - ./config:/config 
      - ./logs:/logs 
      - ./storage:/storage 
